import Layout from "@/component/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/a54d553c09cf2.png";
import AnimatedText from "../component/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/component/Icons";
import HireMe from "@/component/HireMe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Madura Prasad | Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Madura Prasad"
                className="w-full h-auto cursor-pointer"
                priority
                sizes="(max-width:768px) 100vw,(max-width:1200px)50vw,50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="I'm not a great programmer, I'm just a good programmer with great habits."
                className="!text-6xl !text-left cursor-pointer"
              />
              <p className="my-4 text-base font-medium cursor-pointer">
                My career objective is to become a successful software engineer
                by using my knowledge and skills to develop innovative software
                solutions that address the requirements of businesses and
                end-users.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Madura Prasad-Resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border border-bold border-transparent hover:border-dark  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  download={true}
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                  href="https://www.linkedin.com/in/madura-prasad/"
                  target={"_blank"}
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
